### ISSUE TITLE
Pylint 2.4.4 support

### ISSUE THREAD

**Issue by zhaqenl** [OCA/pylint-odoo#281]
In light of [this issue](https://github.com/flycheck/flycheck/issues/1746#issuecomment-619356555) regarding the linter displaying output in HTML (which is not expected) in Pylint 2.3.0, is there any news regarding support for Pylint 2.4.4?

Installing `pylint-odoo` via `pip install pylint-odoo` reverts my Pylint back to 2.3.0. I manually upgraded it to 2.4.4 via `pip install --upgrade pylint`. However, putting `pylint_odoo` under `~/.pylintrc`’s `load-plugins` makes `pylint` produce the following error whenever it is ran:

```
Traceback (most recent call last):
  File "/home/devdesk4/.local/lib/python3.5/site-packages/pylint_plugin_utils/__init__.py", line 3, in <module>
    from pylint.utils import UnknownMessage
ImportError: cannot import name 'UnknownMessage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/devdesk4/.local/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/devdesk4/.local/lib/python3.5/site-packages/pylint/__init__.py", line 23, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/devdesk4/.local/lib/python3.5/site-packages/pylint/lint.py", line 1686, in __init__
    linter.load_plugin_modules(plugins)
  File "/home/devdesk4/.local/lib/python3.5/site-packages/pylint/lint.py", line 660, in load_plugin_modules
    module = modutils.load_module_from_name(modname)
  File "/home/devdesk4/.local/lib/python3.5/site-packages/astroid/modutils.py", line 202, in load_module_from_name
    return load_module_from_modpath(dotted_name.split("."), path, use_sys)
  File "/home/devdesk4/.local/lib/python3.5/site-packages/astroid/modutils.py", line 245, in load_module_from_modpath
    module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
  File "/usr/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/devdesk4/.local/lib/python3.5/site-packages/pylint_odoo/__init__.py", line 3, in <module>
    from . augmentations.main import apply_augmentations
  File "/home/devdesk4/.local/lib/python3.5/site-packages/pylint_odoo/augmentations/__init__.py", line 1, in <module>
    from . import main
  File "/home/devdesk4/.local/lib/python3.5/site-packages/pylint_odoo/augmentations/main.py", line 4, in <module>
    from pylint_plugin_utils import suppress_message
  File "/home/devdesk4/.local/lib/python3.5/site-packages/pylint_plugin_utils/__init__.py", line 5, in <module>
    from pylint.utils import UnknownMessageError as UnknownMessage
ImportError: cannot import name 'UnknownMessageError'
```

**Comment by HviorForgeFlow** [comment]
if you are planning to use pylint > 2.3.0 you should use pylint-plogin-utils >= 0.6

**Comment by HviorForgeFlow** [comment]
@moylop260 could we bump up versions, it seems that standard OCA pre-commit install by default `pylint==2.5.2` which is not compatible with `pylint-plugin-utils==0.5`

You can reproduce it using ```pre-commit autoupdate``` on any OCA repo.

**Comment by zhaqenl** [comment]
> if you are planning to use pylint > 2.3.0 you should use pylint-plogin-utils >= 0.6

How do I go about using this, should I simply install this via `pip`, then retry using `pyling-odoo`?

**Comment by HviorForgeFlow** [comment]
I would use `pip install pylint-plugin-utils==0.6`
But I'm not sure that pylint-odoo is compatible with new pylint versions

**Comment by Yenthe666** [comment]
It would be great if versions are bumped up since pylint is already at 2.5.3 (https://pypi.org/project/pylint/) and this app still only works with 2.3.0

**Comment by moylop260** [comment]
Old pylint version is using 
 - `message.checker.name`
New one:
 - `message.msgid`

I have created dual compatibility and update all requirements here:
 - https://github.com/OCA/pylint-odoo/pull/285

**Comment by Agilis-Enterprise-Solutions** [comment]
The issue is now fixed, thanks! :)

**Comment by zhaqenl** [comment]
The issue is now fixed, thanks! :)

**Comment by Yajo** [comment]
This hasn't been released yet, right? Could you please?
